### ISSUE TITLE
Echo_Sampler Error: module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by yorkane** [antgroup/echomimic_v2#38]
I have installed ffmpeg-python python-ffmpeg ffmpeg packages.
```bash
pip install -U ffmpeg-python python-ffmpeg ffmpeg
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.mirrors.ustc.edu.cn/simple/
Requirement already satisfied: ffmpeg-python in /home/aigc/v310/lib/python3.10/site-packages (0.2.0)
Requirement already satisfied: python-ffmpeg in /home/aigc/v310/lib/python3.10/site-packages (2.0.12)
Requirement already satisfied: ffmpeg in /home/aigc/v310/lib/python3.10/site-packages (1.4)
Requirement already satisfied: future in /home/aigc/v310/lib/python3.10/site-packages (from ffmpeg-python) (1.0.0)
Requirement already satisfied: pyee in /home/aigc/v310/lib/python3.10/site-packages (from python-ffmpeg) (12.1.1)
Requirement already satisfied: typing-extensions in /home/aigc/v310/lib/python3.10/site-packages (from python-ffmpeg) (4.12.2)
```

Still got errors logs below:
```log
****** refer in EchoMimic V2 mode!******
loaded temporal unet's pretrained weights from /home/aigc/ComfyUI/models/echo_mimic/unet ...
Load motion module params from /home/aigc/ComfyUI/models/echo_mimic/v2/motion_module.pth
Loaded 453.20928M-parameter motion module
when use echo v2,need choice a pose dir,for get error using default pose !
***** infer length is 120
poses_tensor:torch.Size([1, 3, 120, 512, 512])
!!! Exception during processing !!! module 'ffmpeg' has no attribute 'Error'
Traceback (most recent call last):
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aigc/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/aigc/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 353, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/home/aigc/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/aigc/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 448, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/utils.py", line 82, in process_video_v2
    video = pipe(
  File "/home/aigc/v310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/echomimic_v2/src/pipelines/pipeline_echomimicv2.py", line 466, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/home/aigc/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/audio.py", line 46, in load_audio
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'. Did you mean: 'errors'?
```

**Comment by huang13094467469** [comment]
你这个应该是没有正确设置环境变量

**Comment by mengrang** [comment]
Pls double check your configuration

**Comment by yorkane** [comment]
tried
```
export FFMPEG_PATH=/home/aigc/tool/ffmpeg-4.4
```
Still not work.

Rebuild whole venv environment fix this.
